# Generated by Django 6.0.3 on 2026-03-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="template",
            field=models.CharField(
                choices=[
                    ("modern", "✨ Modern Professional"),
                    ("classic", "📋 Classic Elegant"),
                    ("creative", "🎨 Creative Design"),
                    ("minimal", "⚡ Minimal Clean"),
                ],
                default="modern",
                max_length=20,
            ),
        ),
    ]
