# Generated by Django 6.0.3 on 2026-03-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_cv_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
