# Generated by Django 6.0.4 on 2026-05-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_skillreference_trainingcourse_company_joboffer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingcourse",
            old_name="provider",
            new_name="provider_name",
        ),
        migrations.AddField(
            model_name="trainingcourse",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_courses",
                to="main.company",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "⏳ Pending"),
                    ("reviewed", "👀 Reviewed"),
                    ("accepted", "✅ Accepted"),
                    ("rejected", "❌ Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
