# Generated by Django 6.0.4 on 2026-05-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_provider_trainingcourse_provider_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="cv_photos/"),
        ),
    ]
