# Generated by Django 6.0.4 on 2026-05-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_interview_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="certificate",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
