# Generated by Django 6.0.4 on 2026-05-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_skill_certificate_skill_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="requirements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
