# Generated by Django 6.0.4 on 2026-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_badge_courseaccomplishment"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ai_score",
            field=models.IntegerField(default=0),
        ),
    ]
