# Generated by Django 6.0.4 on 2026-05-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_application_ai_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="github_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="website_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
